# Generated by Django 5.0.7 on 2024-07-24 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='quantity',
            new_name='rating',
        ),
    ]
